project-admission-trial-period-porfolio
Nuri1977/trial-project-review pull request #3
Opened 2021-11-29 10:59 UTC by Nuri1977

# Project from admission period (Portfolio):

1. Navbar added
2. Welcome section added
3. Work section added
4. Footer added

2021-11-29 12:00 UTC, Nuri1977 commented on index.html
> +    <meta name="viewport" content="width=device-width, initial-scale=1.0">
Please add a responsive layout to your project. 
Free CodeCamp's responsive web design course projects are requiring implementing media queries for tablet and mobile view.

2021-11-29 17:25 UTC, Nuri1977 reviewed
### Hi @Nuri1977 

Good job so far! I know you have worked hard on making this milestone But there are some issues that you still need to work on to go to the next project but you are almost there!

# To Highlight
- Your linters are passing 👍 
- Goof commit history 👍 
- The project runs on the machine 👍 
- Your documentation is ok 👍 

# Required changes

-  Kindly check the comments under the review.

# Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

2021-11-29 17:25 UTC, Nuri1977 commented on css/style.css
> +  height: 100vh;
Please change the height of the Welcome section. Your welcome should have the dimensions as in freeCodeCamp's responsive web design course project.

2021-11-29 17:25 UTC, Nuri1977 commented on index.html
> +          <div class="col-md-4">
Please correct the height of your images in the projects sections. Please look at the image below:

![portfolio_im1](https://user-images.githubusercontent.com/58023246/144001154-b8666f60-2d59-462f-b1d3-5e33c8e693b8.jpg)

In your projects section, you have used the Bootstrap grid and the height of the card containers should be the same size.

2021-11-29 17:46 UTC, brytebee requested changes
Hi <STUDENT MENTION> @Nuri1977 👋,

Good job so far coming so far with the progress you've made! 💪💪 
You have <DONE THIS AND THAT>
However, there are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-29 17:46 UTC, brytebee commented on index.html
> +            <div class="project-tile card border-0">
- [ ] **Required** I highly recommend adding more information to support why a change is necessary. This helps the aids in making the changes requested.
- [ ] **Optional** As much as possible, you could employ the use of emojis to express your desired changes.

2021-11-30 07:57 UTC, Nuri1977 commented on index.html
> +          <div class="col-md-4">
Thank you for your instructions.

2021-11-30 08:07 UTC, elyor-doniyorov approved these changes
Hi @Nuri1977, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-30 08:55 UTC, merged